// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Transactions struct {
	TransactionHash    string         `json:"transaction_hash"`
	BlockNumber        int64          `json:"block_number"`
	Timestamp          time.Time      `json:"timestamp"`
	GasUsed            int64          `json:"gas_used"`
	GasPriceWei        string         `json:"gas_price_wei"`
	TransactionFeeEth  sql.NullString `json:"transaction_fee_eth"`
	TransactionFeeUsdt sql.NullString `json:"transaction_fee_usdt"`
	EthUsdtPrice       sql.NullString `json:"eth_usdt_price"`
}
